<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Carvera.Core/Carvera.Core.csproj" />
    <ProjectReference Include="../../src/Carvera.Layout/Carvera.Layout.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../layouts/**/*" LinkBase="layouts" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../schema/*.json" LinkBase="schema" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
